package com.k7.mealapp.models.dto

import com.k7.mealapp.model.api.MealAPI

fun MealAPI.convertToPojo() =
    MealDto(
    idMeal = this.idMeal,
    name = this.meal?: "",
    drinkAlternate = this.drinkAlternate?: "",
    category = this.category?: "",
    area = this.area?: "",
    instructions = this.instructions?: "",
    mealThumb = this.mealThumb?: "",
    tags = this.tags?: "",
    youtube = this.youtube?: "",
    ingredient = listOf(
                this.ingredient1 ?: "",
                this.ingredient2 ?: "",
                this.ingredient3 ?: "",
                this.ingredient4 ?: "",
                this.ingredient5 ?: "",
                this.ingredient6 ?: "",
                this.ingredient7 ?: "",
                this.ingredient8 ?: "",
                this.ingredient9 ?: "",
                this.ingredient10?: "",
                this.ingredient11?: "",
                this.ingredient12?: "",
                this.ingredient13?: "",
                this.ingredient14?: "",
                this.ingredient15?: "",
                this.ingredient16?: "",
                this.ingredient17?: "",
                this.ingredient18?: "",
                this.ingredient19?: "",
                this.ingredient20?: "",
    ),
    measure= listOf(
            this.measure1 ?: "",
            this.measure2 ?: "",
            this.measure3 ?: "",
            this.measure4 ?: "",
            this.measure5 ?: "",
            this.measure6 ?: "",
            this.measure7 ?: "",
            this.measure8 ?: "",
            this.measure9 ?: "",
            this.measure10?: "",
            this.measure11?: "",
            this.measure12?: "",
            this.measure13?: "",
            this.measure14?: "",
            this.measure15?: "",
            this.measure16?: "",
            this.measure17?: "",
            this.measure18?: "",
            this.measure19?: "",
            this.measure20?: "",
    ),
    source = this.source?: "",
    imageSource = this.imageSource?: "",
    creativeCommonsConfirmed = this.creativeCommonsConfirmed?: "",
    dateModified = this.dateModified?: ""
    )

