package com.k7.mealapp.persistent

object MealDatabaseContract {

    const val DATABASE_NAME = "Meals.db"

    object Meal {
        const val TABLE_NAME = "meals"
        const val COLUMN_MEAL_ID = "meal_id"
        const val COLUMN_MEAL_NAME = "meal_name"
        const val COLUMN_MEAL_CATEGORY = "meal_category"
        const val COLUMN_DRINK_ALTERNATE = "drink_alternate"
        const val COLUMN_MEAL_AREA = "meal_area"
        const val COLUMN_MEAL_INSTRUCTIONS = "meal_instructions"
        const val COLUMN_MEAL_THUMB_URL = "meal_thumb_url"
        const val COLUMN_MEAL_TAGS = "meal_tags"
        const val COLUMN_MEAL_INGREDIENT_1 = "meal_ingredient_1"
        const val COLUMN_MEAL_INGREDIENT_2 = "meal_ingredient_2"
        const val COLUMN_MEAL_INGREDIENT_3 = "meal_ingredient_3"
        const val COLUMN_MEAL_INGREDIENT_4 = "meal_ingredient_4"
        const val COLUMN_MEAL_INGREDIENT_5 = "meal_ingredient_5"
        const val COLUMN_MEAL_INGREDIENT_6 = "meal_ingredient_6"
        const val COLUMN_MEAL_INGREDIENT_7 = "meal_ingredient_7"
        const val COLUMN_MEAL_INGREDIENT_8 = "meal_ingredient_8"
        const val COLUMN_MEAL_INGREDIENT_9 = "meal_ingredient_9"
        const val COLUMN_MEAL_INGREDIENT_10 = "meal_ingredient_10"
        const val COLUMN_MEAL_INGREDIENT_11 = "meal_ingredient_11"
        const val COLUMN_MEAL_INGREDIENT_12 = "meal_ingredient_12"
        const val COLUMN_MEAL_INGREDIENT_13 = "meal_ingredient_13"
        const val COLUMN_MEAL_INGREDIENT_14 = "meal_ingredient_14"
        const val COLUMN_MEAL_INGREDIENT_15 = "meal_ingredient_15"
        const val COLUMN_MEAL_INGREDIENT_16 = "meal_ingredient_16"
        const val COLUMN_MEAL_INGREDIENT_17 = "meal_ingredient_17"
        const val COLUMN_MEAL_INGREDIENT_18 = "meal_ingredient_18"
        const val COLUMN_MEAL_INGREDIENT_19 = "meal_ingredient_19"
        const val COLUMN_MEAL_INGREDIENT_20 = "meal_ingredient_20"
        const val COLUMN_MEAL_MEASURE_1 = "meal_measure_1"
        const val COLUMN_MEAL_MEASURE_2 = "meal_measure_2"
        const val COLUMN_MEAL_MEASURE_3 = "meal_measure_3"
        const val COLUMN_MEAL_MEASURE_4 = "meal_measure_4"
        const val COLUMN_MEAL_MEASURE_5 = "meal_measure_5"
        const val COLUMN_MEAL_MEASURE_6 = "meal_measure_6"
        const val COLUMN_MEAL_MEASURE_7 = "meal_measure_7"
        const val COLUMN_MEAL_MEASURE_8 = "meal_measure_8"
        const val COLUMN_MEAL_MEASURE_9 = "meal_measure_9"
        const val COLUMN_MEAL_MEASURE_10 = "meal_measure_10"
        const val COLUMN_MEAL_MEASURE_11 = "meal_measure_11"
        const val COLUMN_MEAL_MEASURE_12 = "meal_measure_12"
        const val COLUMN_MEAL_MEASURE_13 = "meal_measure_13"
        const val COLUMN_MEAL_MEASURE_14 = "meal_measure_14"
        const val COLUMN_MEAL_MEASURE_15 = "meal_measure_15"
        const val COLUMN_MEAL_MEASURE_16 = "meal_measure_16"
        const val COLUMN_MEAL_MEASURE_17 = "meal_measure_17"
        const val COLUMN_MEAL_MEASURE_18 = "meal_measure_18"
        const val COLUMN_MEAL_MEASURE_19 = "meal_measure_19"
        const val COLUMN_MEAL_MEASURE_20 = "meal_measure_20"
        const val COLUMN_MEAL_LAST_VIEW = "meal_last_view"

    }

}