package com.k7.mealapp.persistent

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = MealDatabaseContract.Meal.TABLE_NAME)

class MealEntity (
    @PrimaryKey
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_ID)
    var id: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_NAME)
    var mealName: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_CATEGORY)
    var mealCategory: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_DRINK_ALTERNATE)
    var mealDrinkAlternate: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_AREA)
    var mealArea: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INSTRUCTIONS)
    var mealInstructions: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_THUMB_URL)
    var mealThumbURL: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_TAGS)
    var mealTags: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_1)
    var mealIngredient_1: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_2)
    var mealIngredient_2: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_3)
    var mealIngredient_3: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_4)
    var mealIngredient_4: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_5)
    var mealIngredient_5: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_6)
    var mealIngredient_6: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_7)
    var mealIngredient_7: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_8)
    var mealIngredient_8: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_9)
    var mealIngredient_9: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_10)
    var mealIngredient_10: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_11)
    var mealIngredient_11: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_12)
    var mealIngredient_12: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_13)
    var mealIngredient_13: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_14)
    var mealIngredient_14: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_15)
    var mealIngredient_15: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_16)
    var mealIngredient_16: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_17)
    var mealIngredient_17: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_18)
    var mealIngredient_18: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_19)
    var mealIngredient_19: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_INGREDIENT_20)
    var mealIngredient_20: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_1)
    var mealMeasure_1: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_2)
    var mealMeasure_2: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_3)
    var mealMeasure_3: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_4)
    var mealMeasure_4: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_5)
    var mealMeasure_5: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_6)
    var mealMeasure_6: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_7)
    var mealMeasure_7: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_8)
    var mealMeasure_8: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_9)
    var mealMeasure_9: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_10)
    var mealMeasure_10: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_11)
    var mealMeasure_11: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_12)
    var mealMeasure_12: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_13)
    var mealMeasure_13: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_14)
    var mealMeasure_14: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_15)
    var mealMeasure_15: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_16)
    var mealMeasure_16: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_17)
    var mealMeasure_17: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_18)
    var mealMeasure_18: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_19)
    var mealMeasure_19: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_MEASURE_20)
    var mealMeasure_20: String,
    @ColumnInfo(name = MealDatabaseContract.Meal.COLUMN_MEAL_LAST_VIEW)
    var mealLastView: String
)